### PR TITLE
Cope with Dancer2 switch to Type::Tiny

### PR DESCRIPTION
**Pull request by SysPete**
And here's the corresponding change for Session.

### CODE REVIEW

**Comment by burnersk** [comment]
And again... Than you!

**Comment by burnersk** [comment]
@SysPete : I hate to ask you about this but:

Can I make you Co-Maintainer? I do not have the time to build a distribution (and for the Dancer2-Plugin-Redis).

**Comment by SysPete** [comment]
@burnersk no problem: I'm happy to take co-maint in order to keep plugins and other external addons in sync with latest D2 releases. If you could also give me a commit bit to the repos that would make things simpler though if you prefer not to that is also find since I am happy to push any changes back to you via PRs.

**Comment by burnersk** [comment]
@SysPete Thank you very much! I have added you as contributor on both GitHub repositories and co-maintainer on PAUSE.

**Comment by SysPete** [comment]
New releases of both now available. I've switched the plugin over to the new plugin2 code which means it cannot be used with Dancer < 0.2 which might upset someone but we'll be doing this to all plugins over the next few months since the old plugin architecture is just too broken.

Thanks for co-maint and I hope you don't mind what I've been up to.

**Pull request merged**
